install: gradle wrapper --gradle-version=4.6
language: java
script:
  - ./gradlew check
  - cp ./build/jacoco/junitPlatformTest.exec ./build/jacoco/test.exec
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
